# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formulaire.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import resFormulaire
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        #Form.resize(582, 677)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 570, 670))
        self.frame.setStyleSheet("QPushButton#boutonSeConnecter{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#boutonSeConnecter:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#boutonSeConnecter:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:(255, 255, 255, 210);\n"
"}\n"
"\n"
"\n"
"QPushButton#boutonRetour{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#boutonRetour:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#boutonRetour:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.fond = QtWidgets.QLabel(self.frame)
        self.fond.setGeometry(QtCore.QRect(10, 10, 550, 650))
        self.fond.setStyleSheet("border-radius : 20px;\n"
"background-image: url(:/images/Fond/fondA.png);")
        self.fond.setText("")
        self.fond.setObjectName("fond")
        self.boutonSeConnecter = QtWidgets.QPushButton(self.frame)
        self.boutonSeConnecter.setGeometry(QtCore.QRect(60, 520, 221, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boutonSeConnecter.setFont(font)
        self.boutonSeConnecter.setObjectName("boutonSeConnecter")
        self.creationCompte = QtWidgets.QLabel(self.frame)
        self.creationCompte.setGeometry(QtCore.QRect(195, 60, 330, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.creationCompte.setFont(font)
        self.creationCompte.setObjectName("creationCompte")
        self.mail = QtWidgets.QLineEdit(self.frame)
        self.mail.setGeometry(QtCore.QRect(120, 270, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.mail.setFont(font)
        self.mail.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"padding-bottom:7px")
        self.mail.setObjectName("mail")
        self.motDePasse = QtWidgets.QLineEdit(self.frame)
        self.motDePasse.setGeometry(QtCore.QRect(120, 330, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.motDePasse.setFont(font)
        self.motDePasse.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px;\n"
"font-weight: bold;")
        self.motDePasse.setEchoMode(QtWidgets.QLineEdit.Password)
        self.motDePasse.setObjectName("motDePasse")
        self.confirmationMotdePasse = QtWidgets.QLineEdit(self.frame)
        self.confirmationMotdePasse.setGeometry(QtCore.QRect(120, 390, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.confirmationMotdePasse.setFont(font)
        self.confirmationMotdePasse.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px;\n"
"font-weight: bold;")
        self.confirmationMotdePasse.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmationMotdePasse.setObjectName("confirmationMotdePasse")
        self.prenom = QtWidgets.QLineEdit(self.frame)
        self.prenom.setGeometry(QtCore.QRect(120, 210, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.prenom.setFont(font)
        self.prenom.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"padding-bottom:7px")
        self.prenom.setObjectName("prenom")
        self.nom = QtWidgets.QLineEdit(self.frame)
        self.nom.setGeometry(QtCore.QRect(120, 150, 350, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.nom.setFont(font)
        self.nom.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"padding-bottom:7px")
        self.nom.setObjectName("nom")
        self.boutonRetour = QtWidgets.QPushButton(self.frame)
        self.boutonRetour.setGeometry(QtCore.QRect(290, 520, 231, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boutonRetour.setFont(font)
        self.boutonRetour.setObjectName("boutonRetour")
        self.iconeMail = QtWidgets.QFrame(self.frame)
        self.iconeMail.setGeometry(QtCore.QRect(80, 280, 32, 30))
        self.iconeMail.setStyleSheet("background-image: url(:/images/Fond/enveloppe.png);")
        self.iconeMail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.iconeMail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.iconeMail.setObjectName("iconeMail")
        self.iconePassword1 = QtWidgets.QFrame(self.frame)
        self.iconePassword1.setGeometry(QtCore.QRect(80, 340, 30, 30))
        self.iconePassword1.setStyleSheet("background-image: url(:/images/Fond/cadenas-verrouille.png);")
        self.iconePassword1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.iconePassword1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.iconePassword1.setObjectName("iconePassword1")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(80, 400, 30, 30))
        self.frame_6.setStyleSheet("background-image: url(:/images/Fond/cadenas-verrouille.png);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.iconeUser1 = QtWidgets.QFrame(self.frame)
        self.iconeUser1.setGeometry(QtCore.QRect(80, 160, 30, 30))
        self.iconeUser1.setStyleSheet("background-image: url(:/images/Fond/utilisateur.png);")
        self.iconeUser1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.iconeUser1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.iconeUser1.setObjectName("iconeUser1")
        self.iconeUser2 = QtWidgets.QFrame(self.frame)
        self.iconeUser2.setGeometry(QtCore.QRect(80, 220, 30, 30))
        self.iconeUser2.setStyleSheet("background-image: url(:/images/Fond/utilisateur.png);")
        self.iconeUser2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.iconeUser2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.iconeUser2.setObjectName("iconeUser2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 450, 181, 41))
        self.label.setStyleSheet("color: red;\n"
"font-size: 16px")
        self.label.setObjectName("label")
        self.mailIncohrent = QtWidgets.QLabel(self.frame)
        self.mailIncohrent.setGeometry(QtCore.QRect(300, 450, 181, 41))
        self.mailIncohrent.setStyleSheet("color: red;\n"
"font-size: 16px")
        self.mailIncohrent.setObjectName("mailIncohrent")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.boutonSeConnecter.setText(_translate("Form", "S\'inscrire"))
        self.creationCompte.setText(_translate("Form", "Création de Compte"))
        self.mail.setPlaceholderText(_translate("Form", "  Mail"))
        self.motDePasse.setPlaceholderText(_translate("Form", "  Mot de Passe"))
        self.confirmationMotdePasse.setPlaceholderText(_translate("Form", "  Confirmation"))
        self.prenom.setPlaceholderText(_translate("Form", "  Prenom"))
        self.nom.setPlaceholderText(_translate("Form", " Nom"))
        self.boutonRetour.setText(_translate("Form", "Retour"))
        self.label.setText(_translate("Form", "Mot de passe différent"))
        self.mailIncohrent.setText(_translate("Form", "Adresse incohérente"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
