# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'responsive_app_formulaire.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import page_formulaire.ressources_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Formulaire(object):
    def page_Formulaire(self, Form):
        Form.setObjectName("Form")
        Form.setWindowTitle("Formulaire")
        Form.resize(500, 623)
        Form.setMinimumSize(QtCore.QSize(460, 500))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setText("Création de votre compte")
        self.horizontalLayout_17.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(400, 0))
        self.frame.setMaximumSize(QtCore.QSize(500, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setMinimumSize(QtCore.QSize(30, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_8.setStyleSheet("background-image: url(:/icones/icones/utilisateur.png);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8.addWidget(self.frame_8)
        self.nom_2 = QtWidgets.QLineEdit(self.frame)
        self.nom_2.setMinimumSize(QtCore.QSize(150, 0))
        self.nom_2.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nom_2.setFont(font)
        self.nom_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:black;\n"
"padding-bottom:7px;\n"
"font-weight: bold;")
        self.nom_2.setObjectName("nom_2")
        self.nom_2.setPlaceholderText(" Nom")
        self.horizontalLayout_8.addWidget(self.nom_2)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setMinimumSize(QtCore.QSize(30, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_9.setStyleSheet("background-image: url(:/icones/icones/utilisateur.png);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9.addWidget(self.frame_9)
        self.prenom_2 = QtWidgets.QLineEdit(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.prenom_2.setFont(font)
        self.prenom_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:black;\n"
"padding-bottom:7px;\n"
"font-weight: bold;")
        self.prenom_2.setObjectName("prenom_2")
        self.prenom_2.setPlaceholderText("  Prenom")
        self.horizontalLayout_9.addWidget(self.prenom_2)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setMinimumSize(QtCore.QSize(32, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_10.setStyleSheet("background-image: url(:/icones/icones/enveloppe.png)")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10.addWidget(self.frame_10)
        self.mail_2 = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mail_2.setFont(font)
        self.mail_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:black;\n"
"padding-bottom:7px;\n"
"font-weight: bold;")
        self.mail_2.setObjectName("mail_2")
        self.mail_2.setPlaceholderText("  Mail")
        self.horizontalLayout_10.addWidget(self.mail_2)
        self.verticalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
        self.frame_12 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_11 = QtWidgets.QFrame(self.frame_12)
        self.frame_11.setMinimumSize(QtCore.QSize(30, 0))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_11.setStyleSheet("background-image: url(:/icones/icones/cadenas-verrouille.png);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_11.addWidget(self.frame_11)
        self.motDePasse_2 = QtWidgets.QLineEdit(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.motDePasse_2.setFont(font)
        self.motDePasse_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:black;\n"
"padding-bottom:7px;\n"
"font-weight: bold;")
        self.motDePasse_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.motDePasse_2.setObjectName("motDePasse_2")
        self.motDePasse_2.setPlaceholderText("  Mot de Passe")

        self.horizontalLayout_11.addWidget(self.motDePasse_2)
        self.verticalLayout.addWidget(self.frame_12, 0, QtCore.Qt.AlignHCenter)
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(30, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_7.setStyleSheet("background-image: url(:/icones/icones/cadenas-verrouille.png);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12.addWidget(self.frame_7)
        self.confirmationMotdePasse_2 = QtWidgets.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirmationMotdePasse_2.setFont(font)
        self.confirmationMotdePasse_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:black;\n"
"padding-bottom:7px;\n"
"font-weight: bold;")
        self.confirmationMotdePasse_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmationMotdePasse_2.setObjectName("confirmationMotdePasse_2")
        self.confirmationMotdePasse_2.setPlaceholderText("  Confirmation")

        self.horizontalLayout_12.addWidget(self.confirmationMotdePasse_2)
        self.verticalLayout.addWidget(self.frame_6, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setStyleSheet("color: red;\n"
"font-size: 16px")
        self.label_2.setObjectName("label_2")
        self.label_2.setText("Mot de passe différent")
        self.label_2.hide()

        self.horizontalLayout_14.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight)
        self.frame_13 = QtWidgets.QFrame(Form)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.mailIncohrent_2 = QtWidgets.QLabel(self.frame_13)
        self.mailIncohrent_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.mailIncohrent_2.setStyleSheet("color: red;\n"
"font-size: 16px")
        self.mailIncohrent_2.setObjectName("mailIncohrent_2")
        self.mailIncohrent_2.setText("Adresse incohérente")
        self.mailIncohrent_2.hide()

        self.horizontalLayout_13.addWidget(self.mailIncohrent_2)
        self.horizontalLayout.addWidget(self.frame_13, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.frame_14 = QtWidgets.QFrame(Form)
        self.frame_14.setMinimumSize(QtCore.QSize(200, 60))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.sinscrire = QtWidgets.QPushButton(self.frame_14)
        self.sinscrire.setMinimumSize(QtCore.QSize(0, 40))
        self.sinscrire.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sinscrire.setFont(font)
        self.sinscrire.setStyleSheet("QPushButton#sinscrire{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#sinscrire:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#sinscrire:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:(255, 255, 255, 210);\n"
"}\n"
"")
        self.sinscrire.setObjectName("sinscrire")
        self.sinscrire.setText("S\'inscrire")

        self.horizontalLayout_15.addWidget(self.sinscrire)
        self.horizontalLayout_2.addWidget(self.frame_14, 0, QtCore.Qt.AlignHCenter)
        self.frame_15 = QtWidgets.QFrame(Form)
        self.frame_15.setMinimumSize(QtCore.QSize(200, 60))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.retour = QtWidgets.QPushButton(self.frame_15)
        self.retour.setMinimumSize(QtCore.QSize(0, 40))
        self.retour.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.retour.setFont(font)
        self.retour.setStyleSheet("QPushButton#retour{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#retour:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#retour:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:(255, 255, 255, 210);\n"
"}\n"
"")
        self.retour.setObjectName("retour")
        self.retour.setText("Retour")

        self.horizontalLayout_16.addWidget(self.retour)
        self.horizontalLayout_2.addWidget(self.frame_15, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)

        QtCore.QMetaObject.connectSlotsByName(Form)







