# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perteMdp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import resMotPassePerdu
from PyQt5 import QtCore, QtGui, QtWidgets


class Password(object):
    def setupUi2(self, Form):
        Form.setObjectName("Form")
        Form.resize(586, 468)
        # Masquer les contours blanc, le nom de la fenêtre et les boutons fermer, réduire etc
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 30, 540, 370))
        self.frame.setStyleSheet("QPushButton#envoyer{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#envoyer:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#envoyer:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:(255, 255, 255, 210);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.fond = QtWidgets.QLabel(self.frame)
        self.fond.setGeometry(QtCore.QRect(20, 20, 500, 330))
        self.fond.setStyleSheet("border-radius : 20px;\n"
"background-image: url(:/images/fond/fondPassword3.png);")
        self.fond.setText("")
        self.fond.setObjectName("fond")
        self.phrase = QtWidgets.QLabel(self.frame)
        self.phrase.setGeometry(QtCore.QRect(115, 40, 310, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.phrase.setFont(font)
        self.phrase.setStyleSheet("white-space: normal;")
        self.phrase.setTextFormat(QtCore.Qt.AutoText)
        self.phrase.setObjectName("phrase")
        self.mail = QtWidgets.QLineEdit(self.frame)
        self.mail.setGeometry(QtCore.QRect(85, 180, 370, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.mail.setFont(font)
        self.mail.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"padding-bottom:7px")
        self.mail.setObjectName("mail")
        self.envoyer = QtWidgets.QPushButton(self.frame)
        self.envoyer.setGeometry(QtCore.QRect(120, 260, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.envoyer.setFont(font)
        self.envoyer.setObjectName("envoyer")
       
        self.fond.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0, yOffset=0, color=QtGui.QColor(234, 221, 186, 100)))
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.phrase.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Réinitialiser votre mot de </span></p><p align=\"center\"><span style=\" font-size:12pt;\">passe</span></p></body></html>"))
        self.mail.setPlaceholderText(_translate("Form", "  adresse email"))
        self.envoyer.setText(_translate("Form", "Envoyer"))



