# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aaaa.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(571, 672)
        Form.resizeevent()
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 570, 670))
        self.frame.setStyleSheet("QPushButton#boutonSeConnecter{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#boutonSeConnecter:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#boutonSeConnecter:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:(255, 255, 255, 210);\n"
"}\n"
"\n"
"\n"
"QPushButton#boutonCreerCompte{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#boutonCreerCompte:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#boutonCreerCompte:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"\n"
"QPushButton#boutonMotDePasseOublie{    \n"
"\n"
"    color: #FFFFFF;\n"
"    border:1px solid rgba(0, 0, 0, 0);\n"
"    border-bottom-color: rgba(105, 118, 132, 200);\n"
"}\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.fond = QtWidgets.QLabel(self.frame)
        self.fond.setGeometry(QtCore.QRect(10, 10, 550, 650))
        self.fond.setStyleSheet("border-radius : 20px;\n"
"background-image: url(:/images/Fond/fondA.png);")
        self.fond.setText("")
        self.fond.setObjectName("fond")
        self.connexion = QtWidgets.QLabel(self.frame)
        self.connexion.setGeometry(QtCore.QRect(320, 80, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.connexion.setFont(font)
        self.connexion.setObjectName("connexion")
        self.image = QtWidgets.QLabel(self.frame)
        self.image.setGeometry(QtCore.QRect(100, 40, 150, 150))
        self.image.setStyleSheet("background-image: url(:/images/Fond/compte.png);")
        self.image.setText("")
        self.image.setObjectName("image")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(93, 390, 21, 21))
        self.label_2.setStyleSheet("background-image: url(:/images/Fond/attention.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(80, 240, 421, 141))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.username = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"padding-bottom:7px")
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px;\n"
"font-weight: bold;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setGeometry(QtCore.QRect(120, 390, 351, 31))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.information = QtWidgets.QLabel(self.widget1)
        self.information.setStyleSheet("color: red;\n"
"font-size: 16px")
        self.information.setObjectName("information")
        self.gridLayout_2.addWidget(self.information, 0, 0, 1, 1)
        self.boutonMotDePasseOublie = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.boutonMotDePasseOublie.setFont(font)
        self.boutonMotDePasseOublie.setStyleSheet("")
        self.boutonMotDePasseOublie.setObjectName("boutonMotDePasseOublie")
        self.gridLayout_2.addWidget(self.boutonMotDePasseOublie, 0, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.frame)
        self.widget2.setGeometry(QtCore.QRect(110, 480, 351, 91))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.boutonSeConnecter = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boutonSeConnecter.setFont(font)
        self.boutonSeConnecter.setObjectName("boutonSeConnecter")
        self.gridLayout_3.addWidget(self.boutonSeConnecter, 0, 0, 1, 1)
        self.boutonCreerCompte = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boutonCreerCompte.setFont(font)
        self.boutonCreerCompte.setObjectName("boutonCreerCompte")
        self.gridLayout_3.addWidget(self.boutonCreerCompte, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.connexion.setText(_translate("Form", "Connexion"))
        self.username.setPlaceholderText(_translate("Form", "  Username"))
        self.password.setPlaceholderText(_translate("Form", "  Password"))
        self.information.setText(_translate("Form", "Informations incorrectes"))
        self.boutonMotDePasseOublie.setText(_translate("Form", "Mot de passe oublié"))
        self.boutonSeConnecter.setText(_translate("Form", "Se connecter"))
        self.boutonCreerCompte.setText(_translate("Form", "Créer un compte"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
