# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'responsive_app_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import page_login.ressource_rc
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QIcon


class Login(object):
    def page_Login(self, page_login):
        page_login.setObjectName("page_login")
        page_login.resize(600, 720)
        page_login.setWindowTitle("Page de Connexion")
        page_login.setMinimumSize(QtCore.QSize(600, 720))
        page_login.setMaximumSize(QtCore.QSize(16777215, 16777215))
        page_login.setStyleSheet("background:white;\n"
"\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(page_login)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout1.addItem(spacerItem)
        self.image = QtWidgets.QLabel(page_login)
        self.image.setMinimumSize(QtCore.QSize(150, 152))
        self.image.setMaximumSize(QtCore.QSize(150, 152))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap(":/images/images/compte.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.horizontalLayout1.addWidget(self.image)
        self.frame_2 = QtWidgets.QFrame(page_login)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout1.addWidget(self.frame_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout1.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(page_login)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connexion = QtWidgets.QLabel(self.frame)
        self.connexion.setMinimumSize(QtCore.QSize(0, 0))
        self.connexion.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.connexion.setFont(font)
        self.connexion.setObjectName("connexion")
        self.connexion.setText("Connexion")

        self.horizontalLayout.addWidget(self.connexion)
        self.horizontalLayout1.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout1.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout1)
        self.verticalLayout2_lineEdit = QtWidgets.QVBoxLayout()
        self.verticalLayout2_lineEdit.setObjectName("verticalLayout2_lineEdit")
        self.usernameFrame = QtWidgets.QFrame(page_login)
        self.usernameFrame.setMinimumSize(QtCore.QSize(500, 0))
        self.usernameFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.usernameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.usernameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.usernameFrame.setObjectName("usernameFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.usernameFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.username = QtWidgets.QLineEdit(self.usernameFrame)
        self.username.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:black;\n"
"font-weight: bold;\n"
"padding-bottom:7px")
        self.username.setObjectName("username")
        self.username.setPlaceholderText("  Username")

        self.verticalLayout_5.addWidget(self.username)
        self.verticalLayout2_lineEdit.addWidget(self.usernameFrame, 0, QtCore.Qt.AlignHCenter)
        self.passwordFrame = QtWidgets.QFrame(page_login)
        self.passwordFrame.setMinimumSize(QtCore.QSize(500, 0))
        self.passwordFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.passwordFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.passwordFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.passwordFrame.setObjectName("passwordFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.passwordFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.password = QtWidgets.QLineEdit(self.passwordFrame)
        self.password.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:black;\n"
"padding-bottom:7px;\n"
"font-weight: bold;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.password.setPlaceholderText("  Password")

        self.verticalLayout_4.addWidget(self.password)
        self.verticalLayout2_lineEdit.addWidget(self.passwordFrame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.verticalLayout2_lineEdit)
        self.horizontalLayout3_icone_info_bouton = QtWidgets.QHBoxLayout()
        self.horizontalLayout3_icone_info_bouton.setObjectName("horizontalLayout3_icone_info_bouton")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout3_icone_info_bouton.addItem(spacerItem3)
        self.iconeFrame = QtWidgets.QFrame(page_login)
        self.iconeFrame.setMinimumSize(QtCore.QSize(35, 35))
        self.iconeFrame.setMaximumSize(QtCore.QSize(35, 35))
        self.iconeFrame.setStyleSheet("")
        self.iconeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.iconeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.iconeFrame.setObjectName("iconeFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.iconeFrame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.icone = QtWidgets.QLabel(self.iconeFrame)
        self.icone.setMinimumSize(QtCore.QSize(20, 20))
        self.icone.setMaximumSize(QtCore.QSize(20, 20))
        self.icone.setText("")
        self.icone.setPixmap(QtGui.QPixmap(":/images/images/attention.png"))
        self.icone.setScaledContents(True)
        self.icone.setObjectName("icone")
        self.icone.hide()
        self.verticalLayout_8.addWidget(self.icone)
        self.horizontalLayout3_icone_info_bouton.addWidget(self.iconeFrame, 0, QtCore.Qt.AlignHCenter)
        self.info_fausseFrame = QtWidgets.QFrame(page_login)
        self.info_fausseFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.info_fausseFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_fausseFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_fausseFrame.setObjectName("info_fausseFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.info_fausseFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.information = QtWidgets.QLabel(self.info_fausseFrame)
        self.information.setMaximumSize(QtCore.QSize(16777215, 40))
        self.information.setStyleSheet("color: red;\n"
"font-size: 16px")
        self.information.setObjectName("information")
        self.information.setText("Informations incorrectes")
        self.information.hide()
        self.verticalLayout_9.addWidget(self.information)
        self.horizontalLayout3_icone_info_bouton.addWidget(self.info_fausseFrame, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout3_icone_info_bouton.addItem(spacerItem4)
        self.motdepasseFrame = QtWidgets.QFrame(page_login)
        self.motdepasseFrame.setMinimumSize(QtCore.QSize(170, 0))
        self.motdepasseFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.motdepasseFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.motdepasseFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.motdepasseFrame.setObjectName("motdepasseFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.motdepasseFrame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.boutonMotDePasseOublie = QtWidgets.QPushButton(self.motdepasseFrame)
        self.boutonMotDePasseOublie.setMinimumSize(QtCore.QSize(200, 20))
        self.boutonMotDePasseOublie.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boutonMotDePasseOublie.setFont(font)
        self.boutonMotDePasseOublie.setStyleSheet("\n"
"QPushButton#boutonMotDePasseOublie{    \n"
"\n"
"    color: black;\n"
"    border:1px solid rgba(0, 0, 0, 0);\n"
"    border-bottom-color: rgba(105, 118, 132, 200);\n"
"}\n"
"\n"
"")
        self.boutonMotDePasseOublie.setObjectName("boutonMotDePasseOublie")
        self.boutonMotDePasseOublie.setText("Mot de passe oublié")

        self.verticalLayout_10.addWidget(self.boutonMotDePasseOublie)
        self.horizontalLayout3_icone_info_bouton.addWidget(self.motdepasseFrame, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout3_icone_info_bouton.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout3_icone_info_bouton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.seConnecterFrame = QtWidgets.QFrame(page_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seConnecterFrame.sizePolicy().hasHeightForWidth())
        self.seConnecterFrame.setSizePolicy(sizePolicy)
        self.seConnecterFrame.setMinimumSize(QtCore.QSize(400, 40))
        self.seConnecterFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.seConnecterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.seConnecterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.seConnecterFrame.setObjectName("seConnecterFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.seConnecterFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.boutonSeConnecter = QtWidgets.QPushButton(self.seConnecterFrame)
        self.boutonSeConnecter.setMinimumSize(QtCore.QSize(0, 40))
        self.boutonSeConnecter.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boutonSeConnecter.setFont(font)
        self.boutonSeConnecter.setStyleSheet("QPushButton#boutonSeConnecter{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#boutonSeConnecter:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#boutonSeConnecter:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:(255, 255, 255, 210);\n"
"}\n"
"")
        self.boutonSeConnecter.setObjectName("boutonSeConnecter")
        self.boutonSeConnecter.setText("Se connecter")

        self.verticalLayout_6.addWidget(self.boutonSeConnecter)
        self.verticalLayout_2.addWidget(self.seConnecterFrame, 0, QtCore.Qt.AlignHCenter)
        self.seCreerCompteFrame = QtWidgets.QFrame(page_login)
        self.seCreerCompteFrame.setMinimumSize(QtCore.QSize(400, 0))
        self.seCreerCompteFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.seCreerCompteFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.seCreerCompteFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.seCreerCompteFrame.setObjectName("seCreerCompteFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.seCreerCompteFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.boutonCreerCompte = QtWidgets.QPushButton(self.seCreerCompteFrame)
        self.boutonCreerCompte.setMinimumSize(QtCore.QSize(0, 40))
        self.boutonCreerCompte.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.boutonCreerCompte.setFont(font)
        self.boutonCreerCompte.setStyleSheet("QPushButton#boutonCreerCompte{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#boutonCreerCompte:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#boutonCreerCompte:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.boutonCreerCompte.setObjectName("boutonCreerCompte")
        self.boutonCreerCompte.setText("Créer un compte")

        self.verticalLayout_7.addWidget(self.boutonCreerCompte)
        self.verticalLayout_2.addWidget(self.seCreerCompteFrame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)


        QtCore.QMetaObject.connectSlotsByName(page_login)













